name: Run tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  vitest:
    name: Run tests
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        node: [ 21 ]

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Set pnpm version
        uses: pnpm/action-setup@v3
        with:
          version: ^8.15.0

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Get packages cache directory path
        id: package-cache-dir-path
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Cache rotation keys
        id: cache-rotation
        shell: bash
        run: |
          echo "YEAR_MONTH=$(/bin/date -u "+%Y%m")" >> $GITHUB_OUTPUT

      - name: Cache node_modules
        uses: actions/cache@v3.2.2
        with:
          path: ${{ steps.package-cache-dir-path.outputs.STORE_PATH }}
          key: ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-${{ steps.cache-rotation.outputs.YEAR_MONTH }}-
            ${{ matrix.os }}-node-v${{ matrix.node }}-pnpm-
            ${{ matrix.os }}-node-v${{ matrix.node }}-
            ${{ matrix.os }}-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
        env:
          HUSKY: '0' # By default do not run HUSKY install

      - name: Test unit
        run: pnpm run test:unit --coverage --minWorkers=1 --maxWorkers=2

      - name: Test unit (Vue 3)
        run: pnpm run test:unit --coverage --minWorkers=1 --maxWorkers=2
        env:
          USE_VUE3: '1'

      - name: CodeCov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: unittests
          files: ./coverage-final.json
